# Generated by Django 4.0.6 on 2022-07-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='modelo',
        ),
    ]
